### ISSUE TITLE
Trace syntax

### ISSUE THREAD

**Issue by aharth** [black-sat/black#111]
Is there documentation on the syntax of traces (`-t` option)?

I suspect it's some JSON syntax but I could not find any documentation.

Thanks!

P.S. Compilation on Debian bookworm worked out of the box!

**Comment by nicola-gigante** [comment]
Hi! 

Indeed there's no documentation of that format, it's more like an internal format for exchange between `black solve` and `black check`. 

But, a perfectly sensible use case is that of generating traces from other sources and then checking them, so I think it's a good idea to add some doc about this format. Thanks for asking!

Meanwhile, to understand the format you can take a look at the output of `black solve` with the `-o json` option.

For example:
```
$ black solve -o json -m -f 'p & X p & X X (q & !p)'
{
    "result": "SAT",
    "k": 1,
    "model": {
        "size": 3,
        "loop": 1,
        "states": [
            {
                "q": "undef",
                "p": "true"
            },
            {
                "q": "undef",
                "p": "true"
            },
            {
                "q": "true",
                "p": "false"
            }
        ]
    }
}
```

The `"loop"` key is an integer that points to the start of the period for infinite traces. It can be omitted for finite traces.
The `"k"`  key is not used by `black check`. The `"undef"` value means the particular proposition is irrelevant in that state.

Let me know if you need anything else.

**Comment by aharth** [comment]
Great, works, thanks for the quick reply!

I have read that future work on BLACK might include model checking, would be great to be able to play around with that! :)

**Comment by nicola-gigante** [comment]
Yes, we are working on that. We are thinking about some concrete syntax to express transition systems where to model check the properties on (something similar to the SMV language, but tailored to BLACK and LTL modulo theories).

Stay tuned :)
