### ISSUE TITLE
Issues compiling BLACK on MacOS Catalina 10.15

### ISSUE THREAD

**Issue by lucageatti** [black-sat/black#15]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:314:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:315:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:316:9: error: no member named 'isfinite' in the global namespace; did
      you mean 'finite'?
using ::isfinite;
      ~~^

**Comment by nicola-gigante** [comment]
Thanks for reporting. Can you please try what happens if you try to compile a minimal example like this:

```
#include <cmath>

int main() {
  return isfinite(3.14);
}
```

with:
```
$ clang example.c -o example
```

**Comment by lucageatti** [comment]
This minimal example work. I paste here the full error.

[ 13%] Built target fmt
[ 18%] Building CXX object src/lib/CMakeFiles/black.dir/src/logic/formula.cpp.o
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/src/logic/formula.cpp:25:
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/include/black/logic/alphabet.hpp:31:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/unordered_map:408:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:314:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:315:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:316:9: error: no member named 'isfinite' in the global namespace; did
      you mean 'finite'?
using ::isfinite;
      ~~^
/usr/local/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/src/logic/formula.cpp:25:
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/include/black/logic/alphabet.hpp:31:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/unordered_map:408:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:320:7: error: no member named 'isgreater' in the global namespace; did
      you mean '::std::greater'?
using ::isgreater;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:728:29: note: '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/src/logic/formula.cpp:25:
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/include/black/logic/alphabet.hpp:31:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/unordered_map:408:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:321:7: error: no member named 'isgreaterequal' in the global
      namespace; did you mean '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:757:29: note: '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/src/logic/formula.cpp:25:
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/include/black/logic/alphabet.hpp:31:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/unordered_map:408:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:323:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:324:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/src/logic/formula.cpp:25:
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/include/black/logic/alphabet.hpp:82:
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/src/lib/include/black/internal/alphabet_impl.hpp:31:
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/external/hopscotch-map/include/tsl/hopscotch_map.h:36:
In file included from /Users/luca/Documents/Universita/Dottorato/tools/black/external/hopscotch-map/include/tsl/hopscotch_hash.h:44:
/Users/luca/Documents/Universita/Dottorato/tools/black/external/hopscotch-map/include/tsl/hopscotch_growth_policy.h:195:18: error: expected unqualified-id
        if(!std::isnormal(next_bucket_count)) {
                 ^
/usr/local/include/math.h:150:5: note: expanded from macro 'isnormal'
    ( sizeof(x) == sizeof(float)  ? __inline_isnormalf((float)(x))       \
    ^
14 errors generated.
make[2]: *** [src/lib/CMakeFiles/black.dir/src/logic/formula.cpp.o] Error 1
make[1]: *** [src/lib/CMakeFiles/black.dir/all] Error 2
make: *** [all] Error 2

**Comment by nicola-gigante** [comment]
Upon further investigation, this error seems related to a bug in macOS or something wrong in the particular installation. See for example [this SO question](https://stackoverflow.com/questions/58628377). I'm closing the issue for now, since BLACK seems to work well on clean Catalina systems.
