### ISSUE TITLE
Compilation steps are not working propertly

### ISSUE THREAD

**Issue by germanbraun** [black-sat/black#39]
3. Create a build directory and cd into it:

`$ mkdir build`

4. Run cmake, pointing it to the build directory

`$ cmake -S . -B build`

the execution of step 4 gives the following Cmake error

CMake Error: The source directory "/home/gab/Documentos/t-crowd/black/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI

I guess that you should use 

`cmake -S ../ -B .`

if you previously did cd into build. according to cmake help

`cmake [options] -S <path-to-source> -B <path-to-build>`

**Comment by nicola-gigante** [comment]
You are right, thanks. Then if you `cd` into the directory you can as well just run `cmake ..`. 
I've updated the installation instructions.
