### ISSUE TITLE
Z3 installed from debian repos not found

### ISSUE THREAD

**Issue by germanbraun** [black-sat/black#40]
I installed Z3 from debian repos but I got `Could NOT find Z3 (missing: Z3_LIBRARY Z3_INCLUDE_DIR)` when compiling black

**Comment by nicola-gigante** [comment]
That's probably a path issue. I'll get into it. Which version of Debian are you using?

**Comment by germanbraun** [comment]
Sorry! here i copied my uname -a

Linux gab 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux

**Comment by nicola-gigante** [comment]
I tried and it works for me. `black` uses the Z3 library.  Have you installed the library development package or just the `z3` binary? 

Try installing it with `apt install libz3-dev` and let me know.

**Comment by germanbraun** [comment]
It's worked after installing libz3-dev. But I got a new error when ran `make`

[ 50%] Building CXX object src/lib/CMakeFiles/black.dir/src/sat/backends/z3.cpp.o
/home/gab/Documentos/t-crowd/black/src/lib/src/sat/backends/z3.cpp: In function ‘void black::sat::backends::error_handler(Z3_context, Z3_error_code)’:
/home/gab/Documentos/t-crowd/black/src/lib/src/sat/backends/z3.cpp:56:56: error: cannot convert ‘Z3_context’ {aka ‘_Z3_context*’} to ‘Z3_error_code’
     fprintf(stderr, "Z3 error: %s\n", Z3_get_error_msg(c, e));
                                                        ^
In file included from /usr/include/z3.h:26,
                 from /home/gab/Documentos/t-crowd/black/src/lib/src/sat/backends/z3.cpp:28:
/usr/include/z3_api.h:5314:53: note:   initializing argument 1 of ‘const char* Z3_get_error_msg(Z3_error_code)’
     Z3_string Z3_API Z3_get_error_msg(Z3_error_code err);
                                       ~~~~~~~~~~~~~~^~~
make[2]: *** [src/lib/CMakeFiles/black.dir/build.make:141: src/lib/CMakeFiles/black.dir/src/sat/backends/z3.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:262: src/lib/CMakeFiles/black.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by nicola-gigante** [comment]
It seems the problem is that Debian has an outdated version of Z3 (4.4), and the API is different from the latest one (4.8). I can think of a workaround to make the code work with both versions, if possible at all.

 In the meantime, you may try to install Z3 from source from their repo. Have a look at [https://github.com/Z3Prover/z3/blob/master/README-CMake.md](https://github.com/Z3Prover/z3/blob/master/README-CMake.md)

**Comment by nicola-gigante** [comment]
A fix is underway on the `fix/debian` branch. I'll merge it as soon as the CI concludes.

**Comment by nicola-gigante** [comment]
PR #41 adds support for Z3 4.4. Now the compilation on Debian stable should go well.. Let me know!

**Comment by germanbraun** [comment]
@nicola-gigante I have successfully installed black after you last changes! Thanks!
