### ISSUE TITLE
should the black compilation require sudo for making install?

### ISSUE THREAD

**Issue by germanbraun** [black-sat/black#42]
On last step:

5. Build, test (optional), and install the tool, I got the following message.

make install
[ 20%] Built target glucose
[ 70%] Built target black
[ 83%] Built target frontend
[ 91%] Built target random_formulas_generator
[100%] Built target crscounter_generator
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libblack.so
CMake Error at src/lib/cmake_install.cmake:47 (file):
  file INSTALL cannot copy file
  "/home/gab/Documentos/t-crowd/black/build/src/lib/libblack.so" to
  "/usr/local/lib/libblack.so".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)

make: *** [Makefile:74: install] Error 1

**Comment by GabVenturato** [comment]
You should run it as sudo (i.e. `sudo make install`) because cmake install default location is `/usr/local/*` which is a system directory. Otherwise you can specify another location (e.g. your home) and run it without sudo.

**Comment by nicola-gigante** [comment]
Yes, probably we should update the docs.
