### ISSUE TITLE
Input syntax documentation could be useful

### ISSUE THREAD

**Issue by GabVenturato** [black-sat/black#66]
It could be useful to have a description of the input accepted by BLACK, e.g., all the operators allowed with their priority.

For example, a formula of the type: `A /\ B -> C` is parsed as `A /\ (B -> C)` and not as `(A /\ B) -> C`. So it's not obvious what one should expect without a detailed description of the operators precedence.

**Comment by nicola-gigante** [comment]
The project wiki now has a page with the syntax with operators precedence and all that, so I'm closing this issue. Thanks for asking!
