### ISSUE TITLE
Feature proposal: Generate random LTL formulas deterministically using a seed option

### ISSUE THREAD

**Issue by caramellaio** [black-sat/black#67]
I am using the random generator of LTL formulas for testing and performance evaluation of my own project. I think that it would be nice to include an option `-s` `--seed` to have a deterministic creation of the LTL formulas.

**Comment by nicola-gigante** [comment]
Hi, thanks for the suggestion! It's a good idea, let us work on it.

**Comment by nicola-gigante** [comment]
Hi!, pull request #68 have been merged, now the random formulas generator has a `--seed` option to specify the seed.
