### ISSUE TITLE
Different results with and without --remove-past option (under finite trace semantics)

### ISSUE THREAD

**Issue by lucageatti** [black-sat/black#93]
With the following formula:
`!( G(a) <-> F(wX(False) & H(Y(a))) )`
the commands
```
black solve --finite
black solve --finite --remove-past
```
give different results. The first returns SAT (which is the correct answer), while the second returns UNSAT.

**Comment by nicola-gigante** [comment]
Thanks for reporting! This problem should be fixed by PR #95. At least the formula you provided now works well. I'll wait for some more tests before merging.
